files:
  - DATA_SRC
  - DATSRCLN
  - DERIV_CD
  - FD_GROUP
  - FOOD_DES
  - FOOTNOTE
  - LANGDESC
  - LANGUAL
  - NUT_DATA
  - NUTR_DEF
  - SRC_CD
  - WEIGHT
  - RANKING
columns:
  DATA_SRC:
    - - DataSrc_ID
      - VARCHAR(6) NOT NULL
    - - Authors
      - VARCHAR(255)
    - - Title
      - VARCHAR(255) NOT NULL
    - - Year
      - VARCHAR(4)
    - - Journal
      - VARCHAR(135)
    - - Vol_City
      - VARCHAR(16)
    - - Issue_State
      - VARCHAR(5)
    - - Start_Page
      - VARCHAR(5)
    - - End_Page
      - VARCHAR(5)
  DATSRCLN:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Nutr_No
      - VARCHAR(3) NOT NULL
    - - DataSrc_ID
      - VARCHAR(6) NOT NULL
  DERIV_CD:
    - - Deriv_Cd
      - VARCHAR(4) NOT NULL
    - - Deriv_Desc
      - VARCHAR(120) NOT NULL
  FD_GROUP:
    - - FdGrp_Cd
      - VARCHAR(4) NOT NULL
    - - FdGrp_Desc
      - VARCHAR(60) NOT NULL
  FOOD_DES:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - FdGrp_Cd
      - VARCHAR(4) NOT NULL
    - - Long_Desc
      - VARCHAR(200) NOT NULL
    - - Shrt_Desc
      - VARCHAR(60) NOT NULL
    - - ComName
      - VARCHAR(100)
    - - ManufacName
      - VARCHAR(65)
    - - Survey
      - VARCHAR(1)
    - - Ref_desc
      - VARCHAR(135)
    - - Refuse
      - INTEGER(2)
    - - SciName
      - VARCHAR(65)
    - - N_Factor
      - REAL(4.2)
    - - Pro_Factor
      - REAL(4.2)
    - - Fat_Factor
      - REAL(4.2)
    - - CHO_Factor
      - REAL(4.2)
  FOOTNOTE:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Footnt_No
      - VARCHAR(4) NOT NULL
    - - Footnt_Typ
      - VARCHAR(1) NOT NULL
    - - Nutr_No
      - VARCHAR(3)
    - - Footnt_Txt
      - VARCHAR(200) NOT NULL
  LANGUAL:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Factor_Code
      - VARCHAR(5) NOT NULL
  LANGDESC:
    - - Factor_Code
      - VARCHAR(5) NOT NULL
    - - Description
      - VARCHAR(140) NOT NULL
  NUT_DATA:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Nutr_No
      - VARCHAR(3) NOT NULL
    - - Nutr_Val
      - REAL(10.3) NOT NULL
    - - Num_Data_Pts
      - REAL(5.0) NOT NULL
    - - Std_Error
      - REAL(8.3)
    - - Src_Cd
      - VARCHAR(2) NOT NULL
    - - Deriv_Cd
      - VARCHAR(4)
    - - Ref_NDB_No
      - VARCHAR(5)
    - - Add_Nutr_Mark
      - VARCHAR(1)
    - - Num_Studies
      - INTEGER(2)
    - - Min
      - REAL(10.3)
    - - Max
      - REAL(10.3)
    - - DF
      - INTEGER(4)
    - - Low_EB
      - REAL(10.3)
    - - Up_EB
      - REAL(10.3)
    - - Stat_cmt
      - VARCHAR(10)
    - - AddMod_Date
      - VARCHAR(10)
    - - CC
      - VARCHAR(1)
  NUTR_DEF:
    - - Nutr_No
      - VARCHAR(3) NOT NULL
    - - Units
      - VARCHAR(7) NOT NULL
    - - Tagname
      - VARCHAR(20)
    - - NutrDesc
      - VARCHAR(60) NOT NULL
    - - Num_Dec
      - VARCHAR(1) NOT NULL
    - - SR_Order
      - INTEGER(6) NOT NULL
  SRC_CD:
    - - Src_Cd
      - VARCHAR(2) NOT NULL
    - - SrcCd_Desc
      - VARCHAR(60) NOT NULL
  WEIGHT:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Seq
      - VARCHAR(2) NOT NULL
    - - Amount
      - REAL(5.3) NOT NULL
    - - Msre_Desc
      - VARCHAR(84) NOT NULL
    - - GM_Wgt
      - REAL(7.1) NOT NULL
    - - Num_Data_Pts
      - INTEGER(3)
    - - Std_Dev
      - REAL(7.3)
  RANKING:
    - - NDB_No
      - VARCHAR(5) NOT NULL
    - - Google_Hits
      - INTEGER
primary:
  WEIGHT:
    - NDB_No
    - Seq
  SRC_CD:
    - Src_Cd
  NUTR_DEF:
    - Nutr_No
  NUT_DATA:
    - NDB_No
    - Nutr_No
  LANGUAL:
    - NDB_No
    - Factor_Code
  LANGDESC:
    - Factor_Code
  FOOTNOTE: []
  FOOD_DES:
    - NDB_No
  FD_GROUP:
    - FdGrp_Cd
  DERIV_CD:
    - Deriv_Cd
  DATSRCLN:
    - NDB_No
    - Nutr_No
    - DataSrc_ID
  DATA_SRC:
    - DataSrc_ID
  RANKING:
    - NDB_No
relations:
  FOOD_DES: []
  FOOTNOTE:
    - - NDB_No
      - FOOD_DES
  NUT_DATA:
    - - NDB_No
      - FOOD_DES
  WEIGHT:
    - - NDB_No
      - FOOD_DES
  LANGUAL:
    - - NDB_No
      - FOOD_DES
  FD_GROUP:
    - - FdGrp_Cd
      - FOOD_DES
  LANGDESC:
    - - Factor_Code
      - LANGUAL
  NUTR_DEF:
    - - Nutr_No
      - NUT_DATA
  SRC_CD:
    - - Src_Cd
      - NUT_DATA
  DERIV_CD:
    - - Deriv_Cd
      - NUT_DATA
  DATSRCLN:
    - - NDB_No
      - NUT_DATA
    - - Nutr_No
      - NUTR_DEF
  DATA_SRC:
    - - DataSrc_ID
      - DATSRCLN
  RANKING:
    - - NDB_No
      - FOOD_DES
